site_name: Portfolio
site_description: A collection of my projects and experiences.
site_author: Muhammad Musab
site_url: https://muhammadmusabyaqoob.github.io/My-Portfolio/

theme:
  name: material
  palette:
    primary: blue
    accent: deep purple
  features:
    - content.code.annotate



markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg







extra_css:
  - css/custom.css


# pages
nav:
  - Home: index.md
  - Projects:
      - Machine Learning:
          - Datasets Project: projects/01_Machine_Learning.md
      - Deep Learning: projects/02_Deep_Learning.md 

  # # - Projects: projects.md
  # - Blogs: blogs.md
  # - Skills: skills.md
  # - Resume: resume.md
  # - About: about.md
  # - Contact: contact.md
