site_name: Portfolio
site_description: A collection of my projects and experiences.
site_author: Muhammad Musab

theme: 
  # name: material
  name: mkdocs



# pages
nav:
  - Home: index.md
  # - Projects:
  #     - Project 1: projects/project1.md
  #     - Project 2: projects/project2.md
  #     - Project 3: projects/project3.md
  - Projects: projects.md
  - Blogs: blogs.md
  - Skills: skills.md
  - Resume: resume.md
  - About: about.md
  # - Contact: contact.md